name: "docker_build_and_publish_to_jfrog"
description: "build docker and publish to jfrog repostiroy"
inputs:
  prebuilt-image-name:
    description: "the image name which need to import into build"
    required: false
  repostory-name:
    description: "the name of the repository"
    required: true
  tag:
    description: "the trg of the image"
    required: true
  jfrog-url:
    description: "jfrog repository url"
    required: true
  jfrog-reponame:
    description: "jfrog repository repo name"
    required: true
  jfrog-username:
    description: "jfrog access username"
    required: true
  jfrog-access-token:
    description: "jfrog access token"
    required: true
outputs:
  full-image-name:
    description: "the image name which built successfully"
    value: ${{steps.image-name-tag-generator.outputs.fullname}}
runs:  
  using: "composite"
  steps: 
    - run: echo "::group::setup image name and tag"
      shell: bash
    - run: export IMAGE_NAME="$repostory-name:$tag"
      shell: bash
    - run: export FULL_IMAGE_NAME="${{inputs.jfrog-url}}/${{inputs.jfrog-reponame}}/$IMAGE_NAME"
      shell: bash
    - id: image-name-tag-generator
      run: echo "::set-output name=fullname::${FULL_IMAGE_NAME}"
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::login jfrog repository"
      shell: bash
    - run: echo ${{inputs.jfrog-access-token}} | docker login --username ${{inputs.jfrog-username}} --password-stdin ${{inputs.jfrog-url}}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::build docker file"
      shell: bash
    - run: docker build . --file Dockerfile --build-arg PRE_IMAGE_NAME=${{inputs.prebuilt-image-name}} --build-arg GIT_TAG=$IMAGE_NAME --build-arg BUILT_DATE=$(TZ=":Pacific/Auckland" date +%F-%T) --tag $IMAGE_NAME       
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::push to the jfrog repository"
      shell: bash
    - run: docker tag $IMAGE_NAME $FULL_IMAGE_NAME 
      shell: bash
    - run: docker push $FULL_IMAGE_NAME
      shell: bash
    - run: echo "::endgroup::"
      shell: bash