name: "docker_build_and_publish_to_jfrog"
description: "build docker and publish to jfrog repostiroy"
inputs:
  prebuilt-image-name:
    description: "the image name which need to import into build"
    required: false
  jfrog-username:
    description: "jfrog username"
    required: true
  jfrog-pasword:
    description: "jfrog password"
    required: true
outputs:
  full-image-name:
    description: "the image name which built successfully"
    value: ${{steps.build.outputs.fullname}}
runs:  
  using: "composite"
  steps: 
    - run: echo "::group::setup image name and tag"
      shell: bash
    - run: export IMAGE_NAME="b2b-wsdl2java-objs:$(date +%s)"
      shell: bash
    - id: image-name-tag-generator
      run: echo "::set-output Full_IMAGE_NAME = fullname::sairay.jfrog.io/images-repo/$IMAGE_NAME"
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::login jfrog repository"
      shell: bash
    - run: echo $JF_ARTIFACTORY_1 | docker login --username $DOCKER_USERNAME --password-stdin sairay.jfrog.io
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::build docker file"
      shell: bash
    - run: docker build . --file Dockerfile --build-arg GIT_TAG=$IMAGE_NAME --build-arg BUILT_DATE=$(TZ=":Pacific/Auckland" date +%F-%T) --tag $IMAGE_NAME       
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::group::push to the jfrog repository"
      shell: bash
    - run: docker tag $IMAGE_NAME sairay.jfrog.io/images-repo/$IMAGE_NAME 
      shell: bash
    - run: docker push sairay.jfrog.io/images-repo/$IMAGE_NAME
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    - run: echo "::set-output Full_IMAGE_NAME = full_image_name::sairay.jfrog.io/images-repo/$IMAGE_NAME"
      shell: bash